server:
  port: 5566

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/

  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true

spring:
  application:
    # 指定注册到eureka server上的服务名称
    name: microservice-consumer-movie
#ribbon饿加载，项目启动时就初始化
ribbon:
  eager-load:
    enabled: true
    clients: microservice-provider-user

microservice-provider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule