server:
  port: 5555
spring:
  application:
    # 指定注册到eureka server上的服务名称
    name: microservice-consumer-movie
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/

  instance:
    prefer-ip-address: true

